
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
package = "@netlify/plugin-functions-install-core"

# Environment variables are set in the Netlify UI under Site settings > Environment variables
# DO NOT put actual API keys here in the netlify.toml file

# Add the following environment variable in your Netlify site settings:
# OPENROUTER_API_KEY - Your OpenRouter API key
