
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxssrnyqohzziznpvbyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4c3Nybnlxb2h6eml6bnB2YnliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNjczNTksImV4cCI6MjA2Mjg0MzM1OX0.TbvMnpO9X0DI5c0dmcO4OdP3twKJ1Jys8uvyavgPZFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
